version: "3"
volumes: 
  php-fpm-socket:
  db_store:
services:
  # nginx
  nginx:
    build: ./docker/nginx/
    container_name: naruse_nginx
    ports:
      - 8080:80
    volumes:
      - ./laravel:/work
      - php-fpm-socket:/var/run/php-fpm
    restart: always
    depends_on: 
      - php

  #php-fpm    
  php:
    build: ./docker/php/
    container_name: naruse_php
    volumes:
      - ./laravel:/work
      - php-fpm-socket:/var/run/php-fpm
    depends_on: 
      - db 
  #MySQL
  db:
    build: ./docker/db/
    container_name: naruse_db
    volumes:
      - db_store:/var/lib/mysql
    ports:
      - 3306:3306
